version: '2'
services:
  backend_api_service:
    image: backend-api
    container_name: "backend_api_service"
    build: .
    ports:
      - "4500:3000"
    command: >
      sh -c "npm install -qy && npm run dev"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo_service

  mongo_service:
    container_name: webapp-mongo_service
    image: mvertes/alpine-mongo:latest
    ports:
      - 57099:27017
    volumes:
      - ./storage:/data/db