version: '3'
services:
  backend_api_service:
    image: backend-api
    container_name: "backend_api_service"
    build: .
    networks:
      - backend
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install -qy && npm run dev"
    volumes:
      - ./:/usr/src/app
  mongo:
    restart: always
    image: mongo:latest
    container_name: "backend_mongodb"
    ports:
      - 57099:27017
    volumes:
      - ./storage:/data/db
networks:
  backend:
    driver: bridge